POST http://localhost:3005/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzdWFyaW8gVGVzdCIsImlkIjoiNjdmMTZhYzkxNzM1ZThjOTE4Yjc5MGJlIiwiaWF0IjoxNzQzODc2MDU4fQ.SkYQ5oBuV2WuzY1QK10GBjnLL4L_5_I25x9HF0vfF20

{
    "title": "Este fue",
    "author": "wwwwww",
    "likes": 0,
    "url": "http://localhost"
}